from . import ikasle
from . import gela
from . import gailu
from . import esleipen
from . import asistentzia
from . import kalifikazio
from . import gorabehera
from . import mugimendu
from . import erosketak
